version: '3.9'
services:
  # http://localhost:15672
  #  username: guest password: guest
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'



